apiVersion: v1
kind: Template
metadata:
  name: hello-world-pipeline
  labels:
    app: hello-world

objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: hello-world-pipeline
    spec:
      source:
        type: Git
        git:
          uri: https://github.com/andreaslanderer/openshift-hello-world.git
          ref: master
      strategy:
        jenkinsPipelineStrategy:
          jenkinsfilePath: 'jenkinsfile.groovy'
        type: JenkinsPipeline