apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: hello-world-api-template
  labels:
    app: hello-world-api
    project: jenkins-test

objects:

  ##### DeploymentConfigs
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: hello-world-api
        project: jenkins-test
      name: hello-world-api
    spec:
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        deploymentconfig: hello-world-api
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: hello-world-api
            deploymentconfig: hello-world-api
            project: jenkins-test
        spec:
          containers:
              image: hello-world:latest
              imagePullPolicy: Always
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /actuator/health
                  port: 8083
                  scheme: HTTP
                initialDelaySeconds: 60
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              name: hello-world-api
              ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /actuator/health
                  port: 8083
                  scheme: HTTP
                initialDelaySeconds: 30
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
                terminationMessagePath: /dev/termination-log
                terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers: []

  ##### Services
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: hello-world-api
        project: jenkins-test
      name: hello-world-api
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentconfig: hello-world-api
      sessionAffinity: None
      type: ClusterIP

  ##### Routes
  - apiVersion: v1
    kind: Route
    metadata:
      creationTimestamp: null
      annotations:
        haproxy.router.openshift.io/timeout: 60000ms
      labels:
        app: hello-world-api
        project: jenkins-test
      name: hello-world-api
    spec:
      port:
        targetPort: 8080-tcp
      tls:
        termination: edge
      to:
        kind: Service
        name: hello-world-api