apiVersion: v1
kind: Template
metadata:
  labels:
    app: hello-world-api-docker
  name: hello-world-api-docker

objects:
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      labels:
        app: hello-world-api-docker
      name: hello-world-api-docker
    spec:
      nodeSelector: {}
      output:
        to:
          kind: ImageStreamTag
          name: hello-world:latest
      postCommit: {}
      runPolicy: Parallel
      source:
        contextDir: /
        git:
          uri: https://github.com/andreaslanderer/openshift-hello-world.git
        type: Git
      strategy:
        sourceStrategy:
          from:
            kind: DockerImage
            namespace: openshift
            name: 'java:11'
        type: Source
      triggers: []