apiVersion: v1
kind: Template
metadata:
  labels:
    app: hello-world-api-docker
  name: hello-world-api-docker

objects:
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      labels:
        app: hello-world-api-docker
      name: hello-world-api-docker
    spec:
      output:
        to:
          kind: DockerImage
          name: image-registry.openshift-image-registry.svc:5000/jenkins-test/hello-world-git:latest
      postCommit: {}
      runPolicy: Parallel
      resources:
        limits:
          cpu: 400m
          memory: 0.5Gi
      source:
        contextDir: .
        type: Binary
      strategy:
        sourceStrategy:
          type: Source
          from:
            kind: ImageStreamTag
            namespace: openshift
            name: 'java:11'